# Generated by Django 3.1.4 on 2020-12-06 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=90, verbose_name='название')),
                ('Subtitle', models.CharField(max_length=90, verbose_name='Под название')),
                ('text', models.TextField(verbose_name='текст')),
                ('pub_date_com', models.DateTimeField(default=datetime.datetime(2020, 12, 6, 19, 9, 0, 621418))),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 12, 6, 19, 9, 0, 622430))),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname_us', models.CharField(max_length=70, unique=True, verbose_name='Ник')),
                ('email_us', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('password_us', models.CharField(max_length=100, verbose_name='Пароль')),
                ('root_us', models.BooleanField(default=False, verbose_name='Админ')),
                ('banned', models.IntegerField(default=0, verbose_name='Уровень бана')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_art', models.CharField(max_length=70, verbose_name='автор')),
                ('name_art', models.CharField(max_length=100, verbose_name='название')),
                ('text_art', models.TextField()),
                ('sellf', models.CharField(max_length=3, verbose_name='curs')),
                ('pub_date_art', models.DateTimeField(default=datetime.datetime(2020, 12, 6, 19, 9, 0, 619417))),
                ('img1', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 1')),
                ('img2', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 2')),
                ('img3', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 3')),
                ('img4', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 4')),
                ('img5', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 5')),
                ('img6', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 6')),
                ('img7', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 7')),
                ('img8', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 8')),
                ('img9', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 9')),
                ('img10', models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 10')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='Main.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='exLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Номер урока в своей группе')),
                ('Title', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.CharField(max_length=30, verbose_name='название html файла')),
                ('Type', models.CharField(choices=[('starts', 'Основы'), ('radio', 'Радо Элементы'), ('deleted', 'Удалённые')], default='starts', max_length=30, verbose_name='тип урока')),
                ('Tag', models.ManyToManyField(blank=True, related_name='тэги', to='Main.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Commet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_com', models.CharField(max_length=70, verbose_name='автор')),
                ('text_com', models.TextField()),
                ('pub_date_com', models.DateTimeField(default=datetime.datetime(2020, 12, 6, 19, 9, 0, 621418))),
                ('post_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.post')),
            ],
        ),
    ]
