# Generated by Django 2.2.5 on 2019-09-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
