# Generated by Django 2.2.5 on 2019-09-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_art_art_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_titled',
            field=models.CharField(max_length=200, null=True, verbose_name='Назdвание'),
        ),
    ]
