# Generated by Django 2.2.5 on 2019-09-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_art_art_titled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='art_titled',
        ),
    ]
