# Generated by Django 2.2.5 on 2019-09-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_art_art_titled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='art_title',
            new_name='art_id',
        ),
    ]
