# Generated by Django 2.2.5 on 2019-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20190930_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_text',
            field=models.TextField(null=True),
        ),
    ]
