# Generated by Django 2.2.5 on 2019-09-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_art_art_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='art_id',
            new_name='art_title',
        ),
    ]
