# Generated by Django 2.2.5 on 2019-09-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20190930_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=70, verbose_name='Ник')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, verbose_name='пароль')),
            ],
        ),
        migrations.DeleteModel(
            name='Art',
        ),
    ]
