# Generated by Django 2.2.5 on 2019-10-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_user_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=70, verbose_name='автор')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('imgs', models.ImageField(upload_to='media/images/databse')),
                ('text', models.TextField()),
            ],
        ),
    ]
