# Generated by Django 2.2.5 on 2019-10-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='author_art',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='name_art',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='text_art',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Nickname',
            new_name='Nickname_us',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_us',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_us',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='root',
            new_name='root_us',
        ),
        migrations.RemoveField(
            model_name='article',
            name='imgs',
        ),
        migrations.AddField(
            model_name='article',
            name='imgs_art',
            field=models.ImageField(null=True, upload_to='media/images/databse'),
        ),
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Commet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_com', models.CharField(max_length=70, verbose_name='автор')),
                ('imgs_com', models.ImageField(null=True, upload_to='media/images/databse')),
                ('text_com', models.TextField()),
                ('article_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Article')),
            ],
        ),
    ]
