# Generated by Django 2.2.5 on 2019-10-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20191001_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='imgs_art',
        ),
        migrations.RemoveField(
            model_name='commet',
            name='imgs_com',
        ),
    ]
