# Generated by Django 2.2.5 on 2019-10-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20191003_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_Title', models.CharField(max_length=30)),
            ],
        ),
    ]
