# Generated by Django 2.2.5 on 2019-10-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
