# Generated by Django 2.2.5 on 2019-10-12 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_auto_20191004_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
