# Generated by Django 2.2.5 on 2019-10-12 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_article_pub_date_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 18, 27, 20, 726482, tzinfo=utc)),
        ),
    ]
