# Generated by Django 2.2.5 on 2019-10-12 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20191012_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 21, 32, 31, 27080)),
        ),
    ]
