# Generated by Django 2.2.5 on 2019-10-12 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_auto_20191012_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 21, 39, 18, 387035)),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 21, 39, 18, 387035)),
        ),
    ]
