# Generated by Django 2.2.7 on 2019-12-08 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_auto_20191012_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 18, 22, 30, 356116)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 18, 22, 30, 356116)),
        ),
    ]
