# Generated by Django 2.2.7 on 2019-12-08 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_auto_20191208_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sellf',
            field=models.CharField(default='non', max_length=3, verbose_name='curs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 19, 24, 29, 480741)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 19, 24, 29, 480741)),
        ),
    ]
