# Generated by Django 2.2.7 on 2019-12-08 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_auto_20191208_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=90, verbose_name='название')),
                ('text', models.TextField(verbose_name='текст')),
                ('pub_date_com', models.DateTimeField(default=datetime.datetime(2019, 12, 8, 21, 6, 33, 117316))),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 21, 6, 33, 116307)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 21, 6, 33, 117316)),
        ),
    ]
