# Generated by Django 2.2.7 on 2019-12-16 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_auto_20191208_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Subtitle',
            field=models.CharField(default='', max_length=90, verbose_name='Под название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 22, 26, 24, 173208)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 22, 26, 24, 173208)),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 22, 26, 24, 174208)),
        ),
    ]
