# Generated by Django 2.2.7 on 2019-12-16 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_auto_20191216_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 22, 26, 57, 678344)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 22, 26, 57, 679353)),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 22, 26, 57, 679353)),
        ),
    ]
