# Generated by Django 2.2.7 on 2019-12-21 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_auto_20191216_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='exLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.CharField(max_length=30, verbose_name='название html файла')),
                ('Type', models.CharField(max_length=30, verbose_name='тип урока')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 18, 59, 26, 214398)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 18, 59, 26, 214398)),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 18, 59, 26, 215407)),
        ),
    ]
