# Generated by Django 2.2.7 on 2019-12-22 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_auto_20191221_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='exlesson',
            name='num',
            field=models.IntegerField(default=1, verbose_name='Номер урока в своей группе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 19, 9, 19, 762305)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 19, 9, 19, 762305)),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 19, 9, 19, 763306)),
        ),
    ]
