# Generated by Django 2.2.7 on 2020-01-04 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_auto_20191222_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 1, 5, 1, 24, 6, 870273))),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 1, 24, 6, 869273)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 1, 24, 6, 869273)),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 1, 24, 6, 869273)),
        ),
    ]
