# Generated by Django 2.2.7 on 2020-01-04 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_auto_20200105_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Main.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 1, 50, 42, 369209)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 1, 50, 42, 370200)),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 1, 50, 42, 370200)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 1, 50, 42, 371210)),
        ),
    ]
