# Generated by Django 3.0.3 on 2020-02-20 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20200124_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='exlesson',
            name='Tag',
            field=models.ManyToManyField(related_name='тэги', to='Main.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 0, 28, 48366)),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Main.Tag'),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 0, 28, 49366)),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 0, 28, 49366)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 0, 28, 51366)),
        ),
    ]
