# Generated by Django 3.0.3 on 2020-02-20 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_auto_20200220_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 51, 11, 251647)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 51, 11, 252647)),
        ),
        migrations.AlterField(
            model_name='exlesson',
            name='Tag',
            field=models.ManyToManyField(blank=True, related_name='тэги', to='Main.Tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 51, 11, 253647)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 51, 11, 255647)),
        ),
    ]
