# Generated by Django 3.0.3 on 2020-02-21 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_auto_20200220_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 20, 33, 38, 554800)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 20, 33, 38, 555810)),
        ),
        migrations.AlterField(
            model_name='exlesson',
            name='Type',
            field=models.CharField(choices=[('radio', 'Радо Элементы'), ('starts', 'Основы'), ('deleted', 'удалённые')], default='starts', max_length=30, verbose_name='тип урока'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 20, 33, 38, 556800)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 20, 33, 38, 558810)),
        ),
    ]
