# Generated by Django 3.0.3 on 2020-02-22 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0035_auto_20200221_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img1',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 1'),
        ),
        migrations.AddField(
            model_name='article',
            name='img10',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 10'),
        ),
        migrations.AddField(
            model_name='article',
            name='img2',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 2'),
        ),
        migrations.AddField(
            model_name='article',
            name='img3',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 3'),
        ),
        migrations.AddField(
            model_name='article',
            name='img4',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 4'),
        ),
        migrations.AddField(
            model_name='article',
            name='img5',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 5'),
        ),
        migrations.AddField(
            model_name='article',
            name='img6',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 6'),
        ),
        migrations.AddField(
            model_name='article',
            name='img7',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 7'),
        ),
        migrations.AddField(
            model_name='article',
            name='img8',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 8'),
        ),
        migrations.AddField(
            model_name='article',
            name='img9',
            field=models.ImageField(blank=True, upload_to='images/users/posts', verbose_name='картинка 9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date_art',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 14, 15, 3, 397099)),
        ),
        migrations.AlterField(
            model_name='commet',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 14, 15, 3, 400100)),
        ),
        migrations.AlterField(
            model_name='exlesson',
            name='Type',
            field=models.CharField(choices=[('starts', 'Основы'), ('radio', 'Радо Элементы'), ('deleted', 'Удалённые')], default='starts', max_length=30, verbose_name='тип урока'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date_com',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 14, 15, 3, 400100)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 14, 15, 3, 402110)),
        ),
    ]
